version: '3.8'

services:
  web:
    image: nginx:latest
    environment:
      - VIRTUAL_HOST=cellardoor.test
      - VIRTUAL_PORT=443
    volumes:
      - ./backend:/var/www
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - backend
      - shared_net
  php:
    image: php:fpm
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    networks:
      - backend

networks:
  backend:
    ipam:
      config:
        - subnet: ${DOCKER_IP_SUBNET}
  shared_net:
    external:
      name: proxy_dev_net